version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3316:3306'
    environment:
      - MARIADB_USER=matomo
      - MARIADB_DATABASE=matomo
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - 'mariadb_data:/bitnami'
  matomo:
    image: 'addyvan/matomo:latest'
    ports:
      - '8000:80'
      - '443:443'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_NAME=matomo
      - MATOMO_DATABASE_PASSWORD=password
      - MATOMO_EMAIL=myemail@gmail.com
      - MATOMO_USERNAME=user
      - MATOMO_PASSWORD=password
      - MATOMO_WEBSITE_NAME=account
      - MATOMO_WEBSITE_HOST=https://account.gccollab.ca
    labels:
      kompose.service.type: nodeport
    volumes:
      - 'matomo_data:/bitnami'
    depends_on:
     - mariadb
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local